name: 'Terraform Apply'

on:
  push:
    branches:
      - qas
    paths:
      - "terraform/**"
      - ".github/**"

jobs:
  terraform:
    name: terraform apply
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    defaults:
      run:
        # terraform実行ディレクトリ
        working-directory: ./terraform/environments/${{ github.ref_name }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        aws-region: ap-northeast-1

    # terraformのバージョンを指定
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.8.5

    - name: Terraform Init
      run: terraform init
 
    - name: Terraform Apply
      run: terraform apply -auto-approve